name: Merge Resource and Behavior Packs to Development

on:
  push:
    branches:
      - resource-pack
      - behavior-pack

jobs:
  merge-packs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Branch
        uses: actions/checkout@v2
        with:
          ref: 'development'
          fetch-depth: 0 # Ensure we get all history for merges

      - name: Fetch Resource Pack Changes
        if: github.ref == 'refs/heads/resource-pack'
        run: |
          git fetch origin resource-pack
          git checkout origin/resource-pack -- USS_Missouri_resource_pack/
          git add USS_Missouri_Resource_Pack/
          git commit -m "Merge Resource Pack changes into Development"

      - name: Fetch Behavior Pack Changes
        if: github.ref == 'refs/heads/behavior-pack'
        run: |
          git fetch origin behavior-pack
          git checkout origin/behavior-pack -- USS_Missouri_behavior_pack/
          git add USS_Missouri_Behavior_Pack/
          git commit -m "Merge Behavior Pack changes into Development"

      - name: Push Changes to Development
        run: git push origin development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
