name: Merge to Development

on:
  push:
    branches:
      - resource-pack
      - behavior-pack

jobs:
  merge-to-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Branch
        uses: actions/checkout@v2
        with:
          ref: 'development'
      - name: Merge Changes Based on Branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/resource-pack" ]]; then
            git fetch origin resource-pack
            git merge --no-ff origin/resource-pack -m "Merging changes from Resource Pack into Development"
          elif [[ "${{ github.ref }}" == "refs/heads/behavior-pack" ]]; then
            git fetch origin behavior-pack
            git merge --no-ff origin/behavior-pack -m "Merging changes from Behavior Pack into Development"
          fi
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'development'
